//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: screen.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate `Beagle_ScreenControllerClient`, then call methods of this protocol to make API calls.
public protocol Beagle_ScreenControllerClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Beagle_ScreenControllerClientInterceptorFactoryProtocol? { get }

  func getScreen(
    _ request: Beagle_ScreenRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Beagle_ScreenRequest, Beagle_ViewNode>
}

extension Beagle_ScreenControllerClientProtocol {
  public var serviceName: String {
    return "beagle.ScreenController"
  }

  /// Unary call to getScreen
  ///
  /// - Parameters:
  ///   - request: Request to send to getScreen.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func getScreen(
    _ request: Beagle_ScreenRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Beagle_ScreenRequest, Beagle_ViewNode> {
    return self.makeUnaryCall(
      path: "/beagle.ScreenController/getScreen",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makegetScreenInterceptors() ?? []
    )
  }
}

public protocol Beagle_ScreenControllerClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'getScreen'.
  func makegetScreenInterceptors() -> [ClientInterceptor<Beagle_ScreenRequest, Beagle_ViewNode>]
}

public final class Beagle_ScreenControllerClient: Beagle_ScreenControllerClientProtocol {
  public let channel: GRPCChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Beagle_ScreenControllerClientInterceptorFactoryProtocol?

  /// Creates a client for the beagle.ScreenController service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  public init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Beagle_ScreenControllerClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

public final class Beagle_ScreenControllerTestClient: Beagle_ScreenControllerClientProtocol {
  private let fakeChannel: FakeChannel
  public var defaultCallOptions: CallOptions
  public var interceptors: Beagle_ScreenControllerClientInterceptorFactoryProtocol?

  public var channel: GRPCChannel {
    return self.fakeChannel
  }

  public init(
    fakeChannel: FakeChannel = FakeChannel(),
    defaultCallOptions callOptions: CallOptions = CallOptions(),
    interceptors: Beagle_ScreenControllerClientInterceptorFactoryProtocol? = nil
  ) {
    self.fakeChannel = fakeChannel
    self.defaultCallOptions = callOptions
    self.interceptors = interceptors
  }

  /// Make a unary response for the getScreen RPC. This must be called
  /// before calling 'getScreen'. See also 'FakeUnaryResponse'.
  ///
  /// - Parameter requestHandler: a handler for request parts sent by the RPC.
  public func makegetScreenResponseStream(
    _ requestHandler: @escaping (FakeRequestPart<Beagle_ScreenRequest>) -> () = { _ in }
  ) -> FakeUnaryResponse<Beagle_ScreenRequest, Beagle_ViewNode> {
    return self.fakeChannel.makeFakeUnaryResponse(path: "/beagle.ScreenController/getScreen", requestHandler: requestHandler)
  }

  public func enqueuegetScreenResponse(
    _ response: Beagle_ViewNode,
    _ requestHandler: @escaping (FakeRequestPart<Beagle_ScreenRequest>) -> () = { _ in }
  )  {
    let stream = self.makegetScreenResponseStream(requestHandler)
    // This is the only operation on the stream; try! is fine.
    try! stream.sendMessage(response)
  }

  /// Returns true if there are response streams enqueued for 'getScreen'
  public var hasgetScreenResponsesRemaining: Bool {
    return self.fakeChannel.hasFakeResponseEnqueued(forPath: "/beagle.ScreenController/getScreen")
  }
}

