# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

workspace 'BeagleHelpers'

target 'BeagleScaffold' do
  project 'beagle-scaffold/BeagleScaffold.xcodeproj'

  pod 'BeagleDefaults', :path => '../BeagleDefaults.podspec'
  pod 'Beagle'
end

 target 'BeagleDefaults' do
   project 'beagle-defaults/BeagleDefaults.xcodeproj'

   pod 'Beagle'
 end

 target 'sampleScaffold' do
   project 'beagle-scaffold-sample/sampleScaffold.xcodeproj'

   pod 'BeagleScaffold', :path => '../BeagleScaffold.podspec'
   pod 'YogaKit', :git => 'https://github.com/ZupIT/YogaKit'
 end