# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'BeagleScaffold' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BeagleScaffold
  pod 'Beagle'

  target 'BeagleScaffoldTests' do
    # Pods for testing
  end

end
