name: AWS ECR

on:
    release:
        types: [created]
        tags: 
          - '**-backend'
env:
    IMAGE: beagle-scaffold-bff

jobs:
    ecr-publish:
        name: ECR Publish
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Cache maven dependences
                uses: actions/cache@v2
                env:
                    maven-cache-key: maven-cache
                    maven-path: ~/.m2
                with:
                    path: ${{ env.maven-path }}
                    key: ${{ runner.os }}-build-${{ env.maven-cache-key }}-${{ hashFiles('BeagleScaffold/backend/pom.xml') }}
                    restore-keys: ${{ runner.os }}-build-${{ env.maven-cache-key }}

            -   id: version
                run: echo "::set-output name=release_tag::$(echo $GITHUB_REF | sed 's/refs\/tags\///g' )"
                shell: bash

            -   name: Build Image
                working-directory: BeagleScaffold/backend
                run: mvn clean -B spring-boot:build-image -DskipTests=true -Dspring-boot.build-image.imageName="temp"

            -   name: Login to Amazon ECR
                id: login-ecr
                uses: aws-actions/amazon-ecr-login@v1
            
            -   name: Publish
                env:
                    ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                    VERSION: ${{ steps.version.outputs.release_tag }}
                run: docker tag "temp" "$ECR_REGISTRY/$IMAGE:$VERSION" && docker push "$ECR_REGISTRY/$IMAGE:$VERSION" 
                
            -   name: Configure AWS credentials
                uses: aws-actions/configure-aws-credentials@v1
                with:
                    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    aws-region: sa-east-1
            
            -   name: Update kubeconfig
                run: aws eks update-kubeconfig --name beagle-cluster
                
            -   name: deploy
                env: 
                    ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                    VERSION: ${{ steps.version.outputs.release_tag }}
                run: sed 's/IMAGE/$ECR_REGISTRY\/$IMAGE:$VERSION/' BeagleScaffold/backend/k8s.yml | kubectl -n adoption apply -f -
                
